Repository OpenBioML/chemnlp, pull requests merged in 2023-03, with the labels that each got.

#42 feat: pampa_ncats dataset
  data/pampa_ncats/example_processing_and_templates.ipynb
  data/pampa_ncats/meta.yaml
  data/pampa_ncats/transform.py
Labels: dataset, priority: high

#36 feat: caco2_wang dataset
  data/caco2_wang/example_processing_and_templates.ipynb
  data/caco2_wang/meta.yaml
  data/caco2_wang/transform.py
  requirements.txt
Labels: dataset, priority: high

#43 feat: add flashpoint dataset
  data/flashpoint/meta.yaml
  data/flashpoint/transform.py
Labels: dataset, priority: high

#46 chore: update link setup in transform.py and notebooks
  data/caco2_wang/example_processing_and_templates.ipynb
  data/caco2_wang/transform.py
  data/freesolv/example_processing_and_templates.ipynb
  data/freesolv/transform.py
  data/lipophilicity/example_processing_and_templates.ipynb
  data/lipophilicity/transform.py
  data/pampa_ncats/example_processing_and_templates.ipynb
  data/pampa_ncats/transform.py
Labels: dataset, priority: high

#104 docs: update dataset & readme docs
  CONTRIBUTING.md
  README.md
Labels: Awaiting author contribution

#121 feat: transform.py cleanup to create nice meta.yaml files
  data/caco2_wang/meta.yaml
  data/caco2_wang/transform.py
  data/cav3_t-type_calcium_channels_butkiewicz/meta.yaml
  data/cav3_t-type_calcium_channels_butkiewicz/transform.py
  data/choline_transporter_butkiewicz/meta.yaml
  data/choline_transporter_butkiewicz/transform.py
  data/clintox/meta.yaml
  data/clintox/transform.py
  data/freesolv/meta.yaml
  data/freesolv/transform.py
  data/kcnq2_potassium_channel_butkiewicz/meta.yaml
  data/kcnq2_potassium_channel_butkiewicz/transform.py
  data/ld50_zhu/meta.yaml
  data/ld50_zhu/transform.py
  data/lipophilicity/meta.yaml
  data/lipophilicity/transform.py
  data/m1_muscarinic_receptor_agonists_butkiewicz/meta.yaml
  data/m1_muscarinic_receptor_agonists_butkiewicz/transform.py
  data/m1_muscarinic_receptor_antagonists_butkiewicz/meta.yaml
  data/m1_muscarinic_receptor_antagonists_butkiewicz/transform.py
  data/orexin1_receptor_butkiewicz/meta.yaml
  data/orexin1_receptor_butkiewicz/transform.py
  data/pampa_ncats/meta.yaml
  data/pampa_ncats/transform.py
  data/potassium_ion_channel_kir2_1_butkiewicz/meta.yaml
  data/potassium_ion_channel_kir2_1_butkiewicz/transform.py
  data/serine_threonine_kinase_33_butkiewicz/meta.yaml
  data/serine_threonine_kinase_33_butkiewicz/transform.py
  data/tyrosyl-dna_phosphodiesterase_butkiewicz/meta.yaml
  data/tyrosyl-dna_phosphodiesterase_butkiewicz/transform.py
Labels: enhancement, dataset

#128 feat: implement benchmark field 2
  data/caco2_wang/meta.yaml
  data/caco2_wang/transform.py
  data/cav3_t-type_calcium_channels_butkiewicz/meta.yaml
  data/cav3_t-type_calcium_channels_butkiewicz/transform.py
  data/choline_transporter_butkiewicz/meta.yaml
  data/choline_transporter_butkiewicz/transform.py
  data/clintox/meta.yaml
  data/clintox/transform.py
  data/kcnq2_potassium_channel_butkiewicz/meta.yaml
  data/kcnq2_potassium_channel_butkiewicz/transform.py
  data/ld50_zhu/meta.yaml
  data/ld50_zhu/transform.py
  data/m1_muscarinic_receptor_agonists_butkiewicz/meta.yaml
  data/m1_muscarinic_receptor_agonists_butkiewicz/transform.py
  data/m1_muscarinic_receptor_antagonists_butkiewicz/meta.yaml
  data/m1_muscarinic_receptor_antagonists_butkiewicz/transform.py
  data/orexin1_receptor_butkiewicz/meta.yaml
  data/orexin1_receptor_butkiewicz/transform.py
  data/pampa_ncats/meta.yaml
  data/pampa_ncats/transform.py
  data/potassium_ion_channel_kir2_1_butkiewicz/meta.yaml
  data/potassium_ion_channel_kir2_1_butkiewicz/transform.py
  data/serine_threonine_kinase_33_butkiewicz/meta.yaml
  data/serine_threonine_kinase_33_butkiewicz/transform.py
  data/tyrosyl-dna_phosphodiesterase_butkiewicz/meta.yaml
  data/tyrosyl-dna_phosphodiesterase_butkiewicz/transform.py
  src/chemnlp/data_val/model.py
Labels: enhancement, dataset
