Repository OpenBioML/chemnlp, pull requests merged in 2023-05, with the labels that each got.

#55 Add Carcinogens from TDC
  data/carcinogens/meta.yaml
  data/carcinogens/transform.py
Labels: Awaiting author contribution

#88 Add ADME metabolism from TDC
  data/cyp2c9_substrate_carbonmangels/meta.yaml
  data/cyp2c9_substrate_carbonmangels/transform.py
  data/cyp2d6_substrate_carbonmangels/meta.yaml
  data/cyp2d6_substrate_carbonmangels/transform.py
  data/cyp3a4_substrate_carbonmangels/meta.yaml
  data/cyp3a4_substrate_carbonmangels/transform.py
  data/cyp_p450_1a2_inhibition_veith_et_al/meta.yaml
  data/cyp_p450_1a2_inhibition_veith_et_al/transform.py
  data/cyp_p450_2c19_inhibition_veith_et_al/meta.yaml
  data/cyp_p450_2c19_inhibition_veith_et_al/transform.py
  data/cyp_p450_2c9_inhibition_veith_et_al/meta.yaml
  data/cyp_p450_2c9_inhibition_veith_et_al/transform.py
  data/cyp_p450_2d6_inhibition_veith_et_al/meta.yaml
  data/cyp_p450_2d6_inhibition_veith_et_al/transform.py
  data/cyp_p450_3a4_inhibition_veith_et_al/meta.yaml
  data/cyp_p450_3a4_inhibition_veith_et_al/transform.py
Labels: Awaiting author contribution

#163 Final logo regular in svg
  README.md
  assets/logo/LLcheD.png
  assets/logo/LLcheD.svg
  assets/logo/LLcheM.png
  assets/logo/LLcheM.svg
  assets/logo/chemnlp.png
  assets/logo/chemnlp.svg
Labels: enhancement, Awaiting author contribution

#86 Add ADME Distribution data from TDC
  data/blood_brain_barrier_martins_et_al/meta.yaml
  data/blood_brain_barrier_martins_et_al/transform.py
  data/plasma_protein_binding_rate_astrazeneca/meta.yaml
  data/plasma_protein_binding_rate_astrazeneca/transform.py
  data/volume_of_distribution_at_steady_state_lombardo_et_al/meta.yaml
  data/volume_of_distribution_at_steady_state_lombardo_et_al/transform.py
  src/chemnlp/data_val/model.py
Labels: dataset, chembl_id

#61 Add hERG Central with multiple target
  data/herg_central/meta.yaml
  data/herg_central/transform.py
Labels: Awaiting author contribution, yaml \

#53 Add h erg blocker from TDC
  data/herg_blockers/meta.yaml
  data/herg_blockers/transform.py
Labels: Awaiting author contribution, yaml \

#52 Add h erg karim et al from TDC
  data/herg_karim_et_al/meta.yaml
  data/herg_karim_et_al/transform.py
Labels: Awaiting author contribution, yaml \

#216 Natural text dataset elsevier_oa_cc-by_corpus
  data/elsevier_oa_cc-by_corpus/meta.yaml
  data/elsevier_oa_cc-by_corpus/transform.py
Labels: dataset, Awaiting author contribution

#204 Hypnopump/add rhea v0
  data/rhea_db/meta.yaml
  data/rhea_db/parsed_rhea.zip
  data/rhea_db/transform.py
  pyproject.toml
Labels: needs-review

#233 feat: entos dataset
  .gitignore
  data/orbnet_denali/orbnet_denali_structures/meta.yaml
  data/orbnet_denali/orbnet_denali_structures/transform.py
  data/rhea_db/meta.yaml
  pyproject.toml
  src/chemnlp/data_val/model.py
  src/chemnlp/utils.py
Labels: dataset

#159 uploading nlmchem to data
  data/nlmchem/meta.yaml
  data/nlmchem/transform.py
  src/chemnlp/data_val/model.py
Labels: dataset, Awaiting author contribution

#76 created h2 storage dataset
  data/h2_storage_materials/LICENSE
  data/h2_storage_materials/meta.yaml
  data/h2_storage_materials/processing.ipynb
  data/h2_storage_materials/transform.py
Labels: Awaiting author contribution
